{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-compiler-common",
    "version": "4.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "emdti2vwsvhgvmvmhmgvla6u5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.googlecode.juniversalchardet",
          "module": "juniversalchardet",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-core",
          "version": {
            "requires": "1.0.0-beta09"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-compiler-common-4.2.1.jar",
          "url": "databinding-compiler-common-4.2.1.jar",
          "size": 484234,
          "sha512": "d5e70b44695278b7a3077afb06a50d830add294e74ebba0f3a16bb2c5c1c02d8e41d13f40d7554198c630671ebb7ab0168c96bc48d52ff1ab1b5f606b31e09cd",
          "sha256": "f387c65ebf3b413a89b640fe106c9b8b5165f787637bbf8840b7803f97e9ed48",
          "sha1": "aaba33f6adc2ef79619b4d6401c46d277992fa71",
          "md5": "a1e940dad991c394d72a25572aa66530"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.googlecode.juniversalchardet",
          "module": "juniversalchardet",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-core",
          "version": {
            "requires": "1.0.0-beta09"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-compiler-common-4.2.1.jar",
          "url": "databinding-compiler-common-4.2.1.jar",
          "size": 484234,
          "sha512": "d5e70b44695278b7a3077afb06a50d830add294e74ebba0f3a16bb2c5c1c02d8e41d13f40d7554198c630671ebb7ab0168c96bc48d52ff1ab1b5f606b31e09cd",
          "sha256": "f387c65ebf3b413a89b640fe106c9b8b5165f787637bbf8840b7803f97e9ed48",
          "sha1": "aaba33f6adc2ef79619b4d6401c46d277992fa71",
          "md5": "a1e940dad991c394d72a25572aa66530"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-common-4.2.1-javadoc.jar",
          "url": "databinding-compiler-common-4.2.1-javadoc.jar",
          "size": 421069,
          "sha512": "ed05b825c35a8fc9427ab1d1cd461f2ae770ff589a2035e24bd0ca5e4d8d6406b3c7f7e03d0f5d88b1c612769b3484b749ada5a9cab7f138e984927d587a50b5",
          "sha256": "222157c2833c6168c3aab701d0f8baf7e36d5dc5a517c8ce56a05f58422fd483",
          "sha1": "d41f9e12a236b3fde29afc174cc3667ae3846707",
          "md5": "674e5bf253e1ca53e5642e3af6055f0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-common-4.2.1-sources.jar",
          "url": "databinding-compiler-common-4.2.1-sources.jar",
          "size": 196904,
          "sha512": "9916beb311996ed5f584e7b4684981840766605698567261b198e391daada82f16c7105f1b8bbc5b6eba955e4b166955472ea93f5c3c4c06c18c348fa1919ce8",
          "sha256": "6766844b3659ec3015813aeb50908fef85134d1212e3d937efadd43b6d87fe2e",
          "sha1": "ff1cbd82750e71d2c51c7636442d4d4a2acf46cd",
          "md5": "daeda76e06563ead981ac0b64ef9b199"
        }
      ]
    }
  ]
}
