{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.lint",
    "module": "lint-gradle",
    "version": "27.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "emdti2vwsvhgvmvmhmgvla6u5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "intellij-core",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "kotlin-compiler",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.external.org-jetbrains",
          "module": "uast",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-gradle-api",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.4.15"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "lint-gradle-27.2.1.jar",
          "url": "lint-gradle-27.2.1.jar",
          "size": 112820,
          "sha512": "dbd187ee8432003a0f7c78e695ae732288ab3b27804a4be98389091d83074a7736209dcf2cd567b3f680dff64838f1d2a6419c83e2c5f013c00bfc9ab52f4070",
          "sha256": "45d81d4d62bfc4c0cd01c3e72ed3338497df977d6875b7d48853a35fe5282bad",
          "sha1": "9dd6227af80aa8e79ff3b718c4837a124e638304",
          "md5": "e738d14b663fc13c4b7455aa22e84893"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "intellij-core",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "kotlin-compiler",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.external.org-jetbrains",
          "module": "uast",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-gradle-api",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.4.15"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "lint-gradle-27.2.1.jar",
          "url": "lint-gradle-27.2.1.jar",
          "size": 112820,
          "sha512": "dbd187ee8432003a0f7c78e695ae732288ab3b27804a4be98389091d83074a7736209dcf2cd567b3f680dff64838f1d2a6419c83e2c5f013c00bfc9ab52f4070",
          "sha256": "45d81d4d62bfc4c0cd01c3e72ed3338497df977d6875b7d48853a35fe5282bad",
          "sha1": "9dd6227af80aa8e79ff3b718c4837a124e638304",
          "md5": "e738d14b663fc13c4b7455aa22e84893"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-gradle-27.2.1-javadoc.jar",
          "url": "lint-gradle-27.2.1-javadoc.jar",
          "size": 40175,
          "sha512": "88570a7f623fd88ac40581798fabb07ee2edfdedfe36340aafd75b08ab05e46f2c0006b942769bb5a660dd42438ae04114f5997b7de1184c753a2de35d36a664",
          "sha256": "f74c93a6d5ed8de3a4f07788850caec4fbef7ef00243ca885a87749b75046e63",
          "sha1": "f5f4dabc5b9f54ea8e7857245532f9c4c9dac239",
          "md5": "dc4570071d94cc56236545b0f2865356"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-gradle-27.2.1-sources.jar",
          "url": "lint-gradle-27.2.1-sources.jar",
          "size": 82412,
          "sha512": "a9fbdadeac2388d0caf0d0d8b00eb50fe55d4ec86ed207af925e1b1222ccdb9438c8d80b64dc82cf54991f8c5e8604359840c9e4dd0a6257508a8bf474ab6871",
          "sha256": "ce0f4b10e14a2e70e2072c80801e08c67a4ed89c38f092e1c251ba86d632a938",
          "sha1": "229ba134419fd57fb9b7ec0874844cfb5bda5c80",
          "md5": "9345a1bb8e6aefe09f35f98028bcbbe8"
        }
      ]
    }
  ]
}
