{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-model",
    "version": "4.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "emdti2vwsvhgvmvmhmgvla6u5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "builder-model-4.2.1.jar",
          "url": "builder-model-4.2.1.jar",
          "size": 100458,
          "sha512": "4803731256a9ca5f4ec41adff492926832898329db5ce751620c99cd7b55b916ba70527a415cd459a469df8ee0add362e800e90f856f26c12f459dfc5a7018d7",
          "sha256": "315dcbfc26b5da56d11b627b31ac82c9bfc02a95e656b9c4eb0fd633b15d64e2",
          "sha1": "04f39d22c9d255667388c4fee54c1ec59688be37",
          "md5": "109ac8dd5a6712e6520e06263f75d086"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "builder-model-4.2.1.jar",
          "url": "builder-model-4.2.1.jar",
          "size": 100458,
          "sha512": "4803731256a9ca5f4ec41adff492926832898329db5ce751620c99cd7b55b916ba70527a415cd459a469df8ee0add362e800e90f856f26c12f459dfc5a7018d7",
          "sha256": "315dcbfc26b5da56d11b627b31ac82c9bfc02a95e656b9c4eb0fd633b15d64e2",
          "sha1": "04f39d22c9d255667388c4fee54c1ec59688be37",
          "md5": "109ac8dd5a6712e6520e06263f75d086"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-4.2.1-javadoc.jar",
          "url": "builder-model-4.2.1-javadoc.jar",
          "size": 230167,
          "sha512": "186fb9e5cec741a1343b7e518aa9928c8113a78735f4df08e6fb56997171b228788887995bc96a31bec0147ad50b3d743e7509a2d85829e8968b726a51a8fa10",
          "sha256": "674f3ba9da1d64d3741846fd1e340430efaa075b009566ad7d847963609a92c4",
          "sha1": "a1c9fad0af036a8e50995fa69ddc2b6fe4ba2995",
          "md5": "53e04585607ebabd55ca91d8a5f2d103"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-4.2.1-sources.jar",
          "url": "builder-model-4.2.1-sources.jar",
          "size": 129030,
          "sha512": "00544e3f10cad5cf3f7f7d6026077c6565407a3618b58175ea0efa3f227ed5875c1de3e6603ac99696f2ebecfb8e0d169e16823ed4b268a233dda41785a38b02",
          "sha256": "a2a0b92989308f3e86debbc1dc3c6aeca640d5f02ab73fe16ecfa19373c60e78",
          "sha1": "c24dc5ebd7e1b59b4df69acc5cc76de23b2e795a",
          "md5": "e44a0f44ca892cebbede8ef0b726439c"
        }
      ]
    }
  ]
}
