{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.external.org-jetbrains",
    "module": "uast",
    "version": "27.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "emdti2vwsvhgvmvmhmgvla6u5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uast-27.2.1.jar",
          "url": "uast-27.2.1.jar",
          "size": 2122898,
          "sha512": "d873c42d4855d4a43fda4917d4517fa71289740294750f2f3821d9d017740260e1d08feefe6c1432bce6e39739e63d5080038905dfe8d0de191fea04635c34eb",
          "sha256": "475824900256f7a446ebfbeda0b2ab43b77a9d232d05e7baeaa5193f82fa8d3f",
          "sha1": "62432fe550c33a541248e92c2c6cab9dd2ca5317",
          "md5": "19e76862c96cef11074bc772694ca066"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uast-27.2.1.jar",
          "url": "uast-27.2.1.jar",
          "size": 2122898,
          "sha512": "d873c42d4855d4a43fda4917d4517fa71289740294750f2f3821d9d017740260e1d08feefe6c1432bce6e39739e63d5080038905dfe8d0de191fea04635c34eb",
          "sha256": "475824900256f7a446ebfbeda0b2ab43b77a9d232d05e7baeaa5193f82fa8d3f",
          "sha1": "62432fe550c33a541248e92c2c6cab9dd2ca5317",
          "md5": "19e76862c96cef11074bc772694ca066"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uast-27.2.1-javadoc.jar",
          "url": "uast-27.2.1-javadoc.jar",
          "size": 19514,
          "sha512": "45041b9f8d03640d4e03efdeefa8c985ce74531f3583fe2df8d78a8c8e9e5518a91d513c39acbc881fb3c9c182ef37c7070ae977e9e49bfaf05e01eae2e0b133",
          "sha256": "64fe57ac8b01a0e69cb9dd5f910dec28fa7d97d259c24489ff80bf99083ca715",
          "sha1": "f518680c7d21f19fd32318775a9ecbd20ec28c82",
          "md5": "fcdcff0b195655ed14442510e57087fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uast-27.2.1-sources.jar",
          "url": "uast-27.2.1-sources.jar",
          "size": 303267,
          "sha512": "5268b5d58679e63df0d8ccf5c65dbc63bad61390ec3fae12882e065dd4df096f44336cea52dd4c3748c8c8288f5195b0bb9815734edd5940a408bfbb1d8c36d6",
          "sha256": "0369fd002d5b5d494ccb95667f3ffc7f60f60370dcff71dfa3a9e09b41185326",
          "sha1": "57f0d2c992d76f6cfe0f4d560b0d5ca20ae407cf",
          "md5": "8167a7d65a2bfff9693cc5ed05234197"
        }
      ]
    }
  ]
}
