{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.lint",
    "module": "lint-checks",
    "version": "27.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "emdti2vwsvhgvmvmhmgvla6u5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.lint",
          "module": "lint-api",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "intellij-core",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "kotlin-compiler",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.external.org-jetbrains",
          "module": "uast",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "lint-checks-27.2.1.jar",
          "url": "lint-checks-27.2.1.jar",
          "size": 4960815,
          "sha512": "6480f6cd78049370d5aa5d601ea6dcfebca194e2155bf09c226a299eeb543abed4a0c1f6e3bed18aa0aecabcc7c84bb20713be01558ab412f36e532dc998b673",
          "sha256": "9f7482bb793020d6debe2345855e81670cfb93b9cc2caa52272e11182f436099",
          "sha1": "7d90d19b2d5ca1eff728efdab16041562c1d1404",
          "md5": "05be0d6d37d2fdd288b7ec2edb8af229"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.lint",
          "module": "lint-api",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "intellij-core",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "kotlin-compiler",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.external.org-jetbrains",
          "module": "uast",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "lint-checks-27.2.1.jar",
          "url": "lint-checks-27.2.1.jar",
          "size": 4960815,
          "sha512": "6480f6cd78049370d5aa5d601ea6dcfebca194e2155bf09c226a299eeb543abed4a0c1f6e3bed18aa0aecabcc7c84bb20713be01558ab412f36e532dc998b673",
          "sha256": "9f7482bb793020d6debe2345855e81670cfb93b9cc2caa52272e11182f436099",
          "sha1": "7d90d19b2d5ca1eff728efdab16041562c1d1404",
          "md5": "05be0d6d37d2fdd288b7ec2edb8af229"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-checks-27.2.1-javadoc.jar",
          "url": "lint-checks-27.2.1-javadoc.jar",
          "size": 563899,
          "sha512": "4fdfb4c593ff0b4292d8dc7677ab4799f6c4ab6186fc971df1b83388ae02ff6f09c97d644f80009d22b86f3244ec6fe05909c984bdd37a0bd3dfc0e50a9aaec7",
          "sha256": "df66037288c428ffed38c472448be4beb9b6221c14140bd21851539916701b7f",
          "sha1": "63adde9ddae9ed381081692df90b2602eee3e342",
          "md5": "a357fddbd7a41121a7337fa28e9b7df9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-checks-27.2.1-sources.jar",
          "url": "lint-checks-27.2.1-sources.jar",
          "size": 4711517,
          "sha512": "617dd1937cd7b49c675067f1012747072f568de6d2437e45aea2a07a55ae3e6ba830e17e4d93790d378d7888af323e44d9e7b9698ab5c681eb9b5da7832a064e",
          "sha256": "edea1a0467e938374e784b47cbd0dc406b74fc385dd7733a513dcaf21abef463",
          "sha1": "fccc6837b3ca902d06f1366ea08dadc6e35538f4",
          "md5": "6c010d932394c6afc80fcfd69ca172aa"
        }
      ]
    }
  ]
}
