{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.lint",
    "module": "lint-api",
    "version": "27.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "emdti2vwsvhgvmvmhmgvla6u5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-model",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "intellij-core",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "kotlin-compiler",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.external.org-jetbrains",
          "module": "uast",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "lint-api-27.2.1.jar",
          "url": "lint-api-27.2.1.jar",
          "size": 793048,
          "sha512": "159e6cc9af8d99726ccc39fc6759b7b7ab6e71bbd13286aba98ad837ab96f4ea3464fe52d24b29ba56dfaea21118efb3a8a47b1a99c9460a00df45fad000c9ea",
          "sha256": "bdf54428cfd512c55000744e60f19d148d9524b1aa5df1f4646d95afb4f591e1",
          "sha1": "f46f7b59562245ac4b18aaff893ea03d1cd739d8",
          "md5": "9f86c30bc5255ff27e7d30cee8984518"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-model",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "intellij-core",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "kotlin-compiler",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.external.org-jetbrains",
          "module": "uast",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "27.2.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "lint-api-27.2.1.jar",
          "url": "lint-api-27.2.1.jar",
          "size": 793048,
          "sha512": "159e6cc9af8d99726ccc39fc6759b7b7ab6e71bbd13286aba98ad837ab96f4ea3464fe52d24b29ba56dfaea21118efb3a8a47b1a99c9460a00df45fad000c9ea",
          "sha256": "bdf54428cfd512c55000744e60f19d148d9524b1aa5df1f4646d95afb4f591e1",
          "sha1": "f46f7b59562245ac4b18aaff893ea03d1cd739d8",
          "md5": "9f86c30bc5255ff27e7d30cee8984518"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-api-27.2.1-javadoc.jar",
          "url": "lint-api-27.2.1-javadoc.jar",
          "size": 137529,
          "sha512": "6c5917d862b81af5d866d1e52208ea930ed575c8bcd6719bff82aa467ff5b2dd2bdd4eeee385ac315fcb6e5502209b8853c52e2dde0a484891c2429a773bff90",
          "sha256": "4fd146e6aa096869f266560176987cc862b65e5cda80a59eacbaa4849506f2a4",
          "sha1": "8cfacf785d96f6980c19929216d72012ba14426f",
          "md5": "23d5d806ded6e6e743204f5a7b9c0518"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-api-27.2.1-sources.jar",
          "url": "lint-api-27.2.1-sources.jar",
          "size": 402811,
          "sha512": "a30e396702428089151c762d24f1c8e2fe8b4b0528cfbafb23535853793643a296d67acedcad3cd4385fabb6a0bc9415b6359fc205be3116f564269017b27ec5",
          "sha256": "b9f4134666fcf570a1f6e0b33e9b007f73ed4f846afa9dd59d913857654218a9",
          "sha1": "0326aa0422985ce7e62b3e0f46ef8390dc8b9ce6",
          "md5": "821b5a7d74df517d781922f8728c98ef"
        }
      ]
    }
  ]
}
