{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.external.com-intellij",
    "module": "intellij-core",
    "version": "27.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "emdti2vwsvhgvmvmhmgvla6u5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "intellij-core-27.2.1.jar",
          "url": "intellij-core-27.2.1.jar",
          "size": 17249003,
          "sha512": "b40d3ad3204a7255b341b99220c43dec50c9cd2622327fbbd8f3504ac6a2770a477e91d296b20a7100ab2558d70784224b941a460a686e7b73cc4b50e57a563a",
          "sha256": "dced6fb2bf3a7fbdcf791c00fc4f61f8532b95d348f254bc5999753b052e8fda",
          "sha1": "2e0f8cb6f0ba9615343eae873b8ea0f424bded99",
          "md5": "0161b0b67deda1a3cf292e820c2d3d07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.intellij.deps",
          "module": "trove4j",
          "version": {
            "requires": "1.0.20181211"
          }
        }
      ],
      "files": [
        {
          "name": "intellij-core-27.2.1.jar",
          "url": "intellij-core-27.2.1.jar",
          "size": 17249003,
          "sha512": "b40d3ad3204a7255b341b99220c43dec50c9cd2622327fbbd8f3504ac6a2770a477e91d296b20a7100ab2558d70784224b941a460a686e7b73cc4b50e57a563a",
          "sha256": "dced6fb2bf3a7fbdcf791c00fc4f61f8532b95d348f254bc5999753b052e8fda",
          "sha1": "2e0f8cb6f0ba9615343eae873b8ea0f424bded99",
          "md5": "0161b0b67deda1a3cf292e820c2d3d07"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "intellij-core-27.2.1-javadoc.jar",
          "url": "intellij-core-27.2.1-javadoc.jar",
          "size": 19291,
          "sha512": "632b0bb50788f0ac290f1f51749232969016ec4a8d251035bae9a3d37d1d2434eed724768c22239ea2456d26098665738f82a6b73169e464809144f6bcabf1be",
          "sha256": "f11c6429aaf79e550355842c838876ee3754af0c1fd2ea7b2df0fd2abba68b6b",
          "sha1": "5b95a3242d21487080fc192be723d5707aa0496f",
          "md5": "f5503b6b9abd6a996c8d461afac13acf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "intellij-core-27.2.1-sources.jar",
          "url": "intellij-core-27.2.1-sources.jar",
          "size": 5472,
          "sha512": "230022a2a44e63b3e5a7a8cc05a6328ab19c5c4027110e4d96bca87ae87cd49fbdeacbb15eab2522830ce6dea09eac2758d34e574b373597719eecb45a335f6f",
          "sha256": "de0463fa05923638141ac19908a6b9fcf10f195f8f957c0522102a826af4cdc5",
          "sha1": "a235156d43c06321e1493b226a84113571ea265e",
          "md5": "d99176a120a0fc63061e6956918bd326"
        }
      ]
    }
  ]
}
