{
  "formatVersion": "1.1",
  "component": {
    "group": "com.appolica",
    "module": "flubber",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wey3pulwrngifn7oqfjjv74tz4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "flubber-1.0.0.aar",
          "url": "flubber-1.0.0.aar",
          "size": 66701,
          "sha512": "e343a656a542ad2f5a7bd57b498f90a05f6f6a0288d521b58c750d8ee379c65ba1ffcaa47622102a5bd71942e36faddba70ddae230d51c9c9762d885f83dd232",
          "sha256": "72ef1ffb6de01a8bbceaadd1d65e8f55edc6b08d93be0d4d1f8355494d7bd9df",
          "sha1": "a781ebb58bd5c9a4208ed26448a8121164364bf0",
          "md5": "df9f86cc4f311d09094b0374c550f013"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-core-ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "16.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "flubber-1.0.0.aar",
          "url": "flubber-1.0.0.aar",
          "size": 66701,
          "sha512": "e343a656a542ad2f5a7bd57b498f90a05f6f6a0288d521b58c750d8ee379c65ba1ffcaa47622102a5bd71942e36faddba70ddae230d51c9c9762d885f83dd232",
          "sha256": "72ef1ffb6de01a8bbceaadd1d65e8f55edc6b08d93be0d4d1f8355494d7bd9df",
          "sha1": "a781ebb58bd5c9a4208ed26448a8121164364bf0",
          "md5": "df9f86cc4f311d09094b0374c550f013"
        }
      ]
    }
  ]
}
