{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-compiler",
    "version": "4.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "emdti2vwsvhgvmvmhmgvla6u5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "com.googlecode.juniversalchardet",
          "module": "juniversalchardet",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-compiler-4.2.1.jar",
          "url": "databinding-compiler-4.2.1.jar",
          "size": 1175252,
          "sha512": "d0e8764961cdb3f771edea69383f63463d77613df6dba2173016bebaca2309c39b32de227e4ae876731dbbc4098d352d536dff2d518437223415fd96443cb4bc",
          "sha256": "3825d65be3762d0c54e74d0a49e9ddd33831b94347e18723989a509d2bebc9e4",
          "sha1": "129cd4e5a4672afffb54db07a619f8d80178c330",
          "md5": "1deccb8c10ad6c1ac365797612861222"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "com.googlecode.juniversalchardet",
          "module": "juniversalchardet",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-compiler-4.2.1.jar",
          "url": "databinding-compiler-4.2.1.jar",
          "size": 1175252,
          "sha512": "d0e8764961cdb3f771edea69383f63463d77613df6dba2173016bebaca2309c39b32de227e4ae876731dbbc4098d352d536dff2d518437223415fd96443cb4bc",
          "sha256": "3825d65be3762d0c54e74d0a49e9ddd33831b94347e18723989a509d2bebc9e4",
          "sha1": "129cd4e5a4672afffb54db07a619f8d80178c330",
          "md5": "1deccb8c10ad6c1ac365797612861222"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-4.2.1-javadoc.jar",
          "url": "databinding-compiler-4.2.1-javadoc.jar",
          "size": 351897,
          "sha512": "e9750eafecb56102d635dbf65de727631643ffe06bbaaebc621c90a9eba3416daba2eb920a75702071b2ee67d4d0defd61f63ecc1e87f01e7f3beefd9bcdebb9",
          "sha256": "0f1175b12f5f09714bec410bf96bc5127a1e587b6c7ec14f5787929dc8a6c8c2",
          "sha1": "08e636d6b2f45e5b7bf176520d5074a45b57ca93",
          "md5": "5e5b9d7737024a3768423563ae528793"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-4.2.1-sources.jar",
          "url": "databinding-compiler-4.2.1-sources.jar",
          "size": 564713,
          "sha512": "1c8eabc6534af2569e77433439547579fc20562e5ee80588e788c8c0326f5127d708789816b7f73e1df2a255fecb9f47cc9680f555d0a8fc8ece08d5c4e7dff0",
          "sha256": "3fb3034c9ce17ab1af01b931d33d75437f8ad72bd0836bd874de8ac9f9f08cbd",
          "sha1": "2833e8da1eb9fe622a3b12fb4b879e86de81d1db",
          "md5": "7a50e02f70608db0b9cfb1b3155a3942"
        }
      ]
    }
  ]
}
